# Generated by Django 3.2.1 on 2022-03-30 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_components', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomponent',
            name='component_name',
            field=models.CharField(max_length=50, verbose_name='Component Name'),
        ),
        migrations.AlterField(
            model_name='usercomponent',
            name='params',
            field=models.JSONField(blank=True, default=dict, verbose_name='Parameters'),
        ),
    ]
