# Generated by Django 3.2.1 on 2022-04-04 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_components', '0002_auto_20220330_0224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercomponent',
            options={'ordering': ['user', 'component_name']},
        ),
    ]
